### ISSUE TITLE
Error when launching the server window

### ISSUE THREAD

**Issue by acse-hx721** [NETL-RIC/pipeline-routing-tool-release#1]
Hi,
I am trying to run the tool as per the instructions but the server window shows the following error, have you encountered this problem before?

`fpdf\__init__.py:39: UserWarning: You have both PyFPDF & fpdf2 installed. Both packages cannot be installed at the same time as they share the same module namespace. To only keep fpdf2, run: pip uninstall --yes pypdf && pip install --upgrade fpdf2`

I checked the python environment on my computer and it doesn't seem to have these two packages installed, so I'm not sure what's causing the problem.

Thanks in advance.

**Comment by sleveckis** [comment]
Good afternoon, we're aware of this issue and will have it corrected in a future release. It's due to both packages being installed in the program itself (not on your system), which doesn't break anything but causes the interpreter to throw a warning. Thanks for the question!
